import Fastify, { type FastifyReply, type FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import { z } from 'zod';
import { fixtureState, type Role } from '../../../packages/domain/src/state.js';

const app = Fastify({ logger: process.env.NODE_ENV !== 'test' });
await app.register(helmet);
await app.register(cors, { origin: process.env.APP_ORIGIN ?? 'http://localhost:5173', credentials: true });
const rid = (reply: FastifyReply) => String(reply.request.id);
function fail(reply: FastifyReply, status: number, code: string, message: string, fieldErrors?: Record<string, string[]>) { return reply.code(status).send({ error: { code, message, ...(fieldErrors ? { fieldErrors } : {}), requestId: rid(reply) } }); }
type Actor = { id: string; role: Role };
function getActor(request: FastifyRequest): Actor | null { const id = request.headers['x-dev-user-id']; const role = request.headers['x-dev-role']; return typeof id === 'string' && (role === 'customer' || role === 'mechanic' || role === 'admin') ? { id, role } : null; }
function auth(request: FastifyRequest, reply: FastifyReply): Actor | null { const a = getActor(request); if (!a) { fail(reply, 401, 'UNAUTHENTICATED', 'A valid development session is required.'); return null; } return a; }
function jobFor(request: FastifyRequest, reply: FastifyReply, a: Actor) { const job = fixtureState.jobs.find((j) => j.id === (request.params as { id: string }).id); if (!job) { fail(reply, 404, 'NOT_FOUND', 'Job not found.'); return null; } if ((a.role === 'customer' && job.customerId !== a.id) || (a.role === 'mechanic' && job.mechanicId !== a.id)) { fail(reply, 403, 'FORBIDDEN', 'You are not allowed to access this job.'); return null; } return job; }

app.get('/health', async () => ({ status: 'ok', contractVersion: '1.1.0', mockMode: process.env.MOCK_MODE === 'true' }));
app.get('/api/v1/session', async (request, reply) => { const a = auth(request, reply); if (!a) return; return { user: a, capabilities: a.role === 'admin' ? ['quotes:write', 'jobs:write', 'catalog:write'] : a.role === 'mechanic' ? ['jobs:read', 'jobs:write', 'messages:write'] : ['vehicles:read', 'requests:write', 'quotes:accept'] }; });
app.get('/api/v1/service-catalog', async () => ({ data: fixtureState.services, meta: { source: process.env.MOCK_MODE === 'true' ? 'fixture' : 'development-adapter' } }));
app.get('/api/v1/vehicles', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can access household vehicles.'); return { data: fixtureState.vehicles.filter((v) => v.customerId === a.id) }; });
const vehicleSchema = z.object({ year: z.number().int().min(1886).max(2100), make: z.string().min(1).max(80), model: z.string().min(1).max(80), mileage: z.number().int().nonnegative().optional(), vin: z.string().length(17).optional() });
app.post('/api/v1/vehicles', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can create vehicles.'); const p = vehicleSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Vehicle input is invalid.', p.error.flatten().fieldErrors); const v = { id: `vehicle-${fixtureState.vehicles.length + 1}`, customerId: a.id, ...p.data }; fixtureState.vehicles.push(v); return reply.code(201).send({ data: v }); });
app.get('/api/v1/vehicles/:id/history', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can access vehicle history.'); const v = fixtureState.vehicles.find((x) => x.id === (request.params as { id: string }).id && x.customerId === a.id); if (!v) return fail(reply, 404, 'NOT_FOUND', 'Vehicle not found.'); return { data: fixtureState.history.filter((h) => h.vehicleId === v.id) }; });
const requestSchema = z.object({ vehicleId: z.string(), category: z.string().min(1), symptoms: z.array(z.string()), notes: z.string().max(4000).optional(), attachmentIds: z.array(z.string()).optional() });
app.post('/api/v1/service-requests', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can submit service requests.'); const p = requestSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Service request input is invalid.', p.error.flatten().fieldErrors); if (!fixtureState.vehicles.some((v) => v.id === p.data.vehicleId && v.customerId === a.id)) return fail(reply, 403, 'FORBIDDEN', 'Vehicle is not in your household.'); const item = { id: `request-${fixtureState.requests.length + 1}`, customerId: a.id, status: 'submitted', ...p.data }; fixtureState.requests.push(item); return reply.code(201).send({ data: item }); });
const uploadSchema = z.object({ fileName: z.string().min(1).max(255), contentType: z.enum(['image/jpeg', 'image/png', 'image/webp', 'video/mp4']), sizeBytes: z.number().int().positive().max(25000000) });
app.post('/api/v1/uploads', async (request, reply) => { const a = auth(request, reply); if (!a) return; const p = uploadSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Upload metadata is invalid.', p.error.flatten().fieldErrors); const item = { id: `upload-${fixtureState.uploads.length + 1}`, ownerId: a.id, status: 'pending_local_adapter', ...p.data }; fixtureState.uploads.push(item); return reply.code(201).send({ data: item, meta: { provider: 'local-safe-adapter', uploadRequired: false } }); });
app.get('/api/v1/quotes/:id', async (request, reply) => { const a = auth(request, reply); if (!a) return; const q = fixtureState.quotes.find((x) => x.id === (request.params as { id: string }).id); if (!q) return fail(reply, 404, 'NOT_FOUND', 'Quote not found.'); if (a.role === 'customer' && q.customerId !== a.id) return fail(reply, 403, 'FORBIDDEN', 'You are not allowed to access this quote.'); return { data: q }; });
app.get('/api/v1/jobs/:id', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = jobFor(request, reply, a); if (!j) return; return { data: j }; });
app.get('/api/v1/jobs/:id/findings', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = jobFor(request, reply, a); if (!j) return; return { data: fixtureState.findings.filter((x) => x.jobId === j.id) }; });
app.get('/api/v1/jobs/:id/messages', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = jobFor(request, reply, a); if (!j) return; return { data: fixtureState.messages.filter((x) => x.jobId === j.id) }; });
const messageSchema = z.object({ body: z.string().min(1).max(4000) });
app.post('/api/v1/jobs/:id/messages', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = jobFor(request, reply, a); if (!j) return; const key = request.headers['idempotency-key']; if (typeof key !== 'string' || key.length < 8) return fail(reply, 422, 'VALIDATION_ERROR', 'Idempotency-Key header is required.'); const p = messageSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Message is invalid.', p.error.flatten().fieldErrors); const item = { id: `message-${fixtureState.messages.length + 1}`, jobId: j.id, senderId: a.id, createdAt: new Date().toISOString(), ...p.data }; fixtureState.messages.push(item); return reply.code(201).send({ data: item }); });
const acceptSchema = z.object({ expectedVersion: z.number().int().positive(), idempotencyKey: z.string().min(8) });
app.post('/api/v1/quotes/:id/accept', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only the customer may accept a quote.'); const q = fixtureState.quotes.find((x) => x.id === (request.params as { id: string }).id); if (!q || q.customerId !== a.id) return fail(reply, 404, 'NOT_FOUND', 'Quote not found.'); const p = acceptSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Acceptance input is invalid.'); if (p.data.expectedVersion !== q.version) return fail(reply, 409, 'STALE_VERSION', 'Quote changed; retrieve the latest version before accepting.'); if (q.status !== 'issued') return fail(reply, 409, 'QUOTE_NOT_ACCEPTABLE', 'Only issued quotes can be accepted.'); q.status = 'accepted'; q.version += 1; return { data: q }; });
app.setErrorHandler((err, request, reply) => { request.log.error(err); return fail(reply, 500, 'INTERNAL_ERROR', 'The server could not complete the request.'); });
await app.listen({ port: Number(process.env.PORT ?? 3000), host: process.env.HOST ?? '127.0.0.1' });
