import 'dotenv/config';
import Fastify, { type FastifyReply, type FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rawBody from 'fastify-raw-body';
import Stripe from 'stripe';
import { z } from 'zod';
import { createRemoteJWKSet, jwtVerify } from 'jose';
import { fixtureState, type Role } from '../../../packages/domain/src/state.js';
import { createDatabase } from '../../../packages/database/src/client.js';
import { createBookingRepository, createInvoiceRepository, createQuoteJobRepository, createRepairRoomRepository, createServiceRequestRepository, createVehicleRepository } from '../../../packages/database/src/repositories.js';

const app = Fastify({ logger: process.env.NODE_ENV !== 'test' });
const database = process.env.MOCK_MODE === 'true' ? null : createDatabase();
const vehicleRepository = database ? createVehicleRepository(database) : null;
const serviceRequestRepository = database ? createServiceRequestRepository(database) : null;
const bookingRepository = database ? createBookingRepository(database) : null;
const repairRoomRepository = database ? createRepairRoomRepository(database) : null;
const invoiceRepository = database ? createInvoiceRepository(database) : null;
const quoteJobRepository = database ? createQuoteJobRepository(database) : null;
const jwks = process.env.AUTH_JWKS_URL ? createRemoteJWKSet(new URL(process.env.AUTH_JWKS_URL)) : null;
const rateWindowMs = Number(process.env.RATE_LIMIT_WINDOW_MS ?? 60_000);
const rateLimitMax = Number(process.env.RATE_LIMIT_MAX ?? 120);
const rateBuckets = new Map<string, { startedAt: number; count: number }>();
app.addHook('onRequest', async (request, reply) => { if (request.url.split('?')[0] === '/api/v1/webhooks/stripe') return; const key = request.ip; const now = Date.now(); const current = rateBuckets.get(key); const bucket = !current || now - current.startedAt >= rateWindowMs ? { startedAt: now, count: 1 } : { startedAt: current.startedAt, count: current.count + 1 }; rateBuckets.set(key, bucket); if (bucket.count > rateLimitMax) { reply.header('Retry-After', Math.ceil((bucket.startedAt + rateWindowMs - now) / 1000)); return reply.code(429).send({ error: { code: 'RATE_LIMITED', message: 'Too many requests.', requestId: String(request.id) } }); } });
if (database) app.addHook('preHandler', async (request, reply) => { if (request.url.split('?')[0] === '/api/v1/webhooks/stripe') return; if (process.env.AUTH_MODE === 'managed') { const authHeader = request.headers.authorization; if (!jwks || !authHeader?.startsWith('Bearer ')) return reply.code(401).send({ error: { code: 'UNAUTHENTICATED', message: 'A valid Supabase session is required.', requestId: String(request.id) } }); try { const verified = await jwtVerify(authHeader.slice(7), jwks, { issuer: process.env.AUTH_ISSUER, audience: process.env.AUTH_AUDIENCE ?? 'authenticated' }); const rows = await database.query<{ id: string; role: Role }>('SELECT u.id, m.role FROM users u JOIN memberships m ON m.user_id = u.id WHERE u.id = $1 ORDER BY CASE m.role WHEN \'admin\' THEN 1 WHEN \'mechanic\' THEN 2 ELSE 3 END LIMIT 1', [verified.payload.sub]); if (!rows[0]) return reply.code(403).send({ error: { code: 'FORBIDDEN', message: 'No business membership exists for this account.', requestId: String(request.id) } }); request.headers['x-dev-user-id'] = rows[0].id; request.headers['x-dev-role'] = rows[0].role; } catch { return reply.code(401).send({ error: { code: 'UNAUTHENTICATED', message: 'The Supabase session is invalid or expired.', requestId: String(request.id) } }); } } else { const devId = request.headers['x-dev-user-id']; if (devId !== 'customer-demo' && devId !== 'mechanic-demo' && devId !== 'admin-demo') return; const email = `${devId}@local.test`; const rows = await database.query<{ id: string }>('SELECT id FROM users WHERE email = $1', [email]); if (rows[0]) request.headers['x-dev-user-id'] = rows[0].id; } });
await app.register(helmet);
await app.register(cors, { origin: process.env.APP_ORIGIN ?? 'http://localhost:5173', credentials: true });
await app.register(rawBody, { field: 'rawBody', global: false, encoding: 'utf8', runFirst: true, routes: ['/api/v1/webhooks/stripe'] });
const rid = (reply: FastifyReply) => String(reply.request.id);
function fail(reply: FastifyReply, status: number, code: string, message: string, fieldErrors?: Record<string, string[]>) { return reply.code(status).send({ error: { code, message, ...(fieldErrors ? { fieldErrors } : {}), requestId: rid(reply) } }); }
type Actor = { id: string; role: Role };
function getActor(request: FastifyRequest): Actor | null { const id = request.headers['x-dev-user-id']; const role = request.headers['x-dev-role']; return typeof id === 'string' && (role === 'customer' || role === 'mechanic' || role === 'admin') ? { id, role } : null; }
function auth(request: FastifyRequest, reply: FastifyReply): Actor | null { const a = getActor(request); if (!a) { fail(reply, 401, 'UNAUTHENTICATED', 'A valid development session is required.'); return null; } return a; }
async function jobFor(request: FastifyRequest, reply: FastifyReply, a: Actor) { const id = (request.params as { id: string }).id; if (database && z.string().uuid().safeParse(id).success) { const rows = await database.query('SELECT id, customer_id AS "customerId", mechanic_id AS "mechanicId", status, version FROM jobs WHERE id = $1 AND (($2 = \'customer\' AND customer_id = $3) OR ($2 = \'mechanic\' AND mechanic_id = $3) OR $2 = \'admin\')', [id, a.role, a.id]); if (!rows[0]) { fail(reply, 404, 'NOT_FOUND', 'Job not found.'); return null; } return rows[0]; } const job = fixtureState.jobs.find((j) => j.id === id); if (!job) { fail(reply, 404, 'NOT_FOUND', 'Job not found.'); return null; } if ((a.role === 'customer' && job.customerId !== a.id) || (a.role === 'mechanic' && job.mechanicId !== a.id)) { fail(reply, 403, 'FORBIDDEN', 'You are not allowed to access this job.'); return null; } return job; }

app.get('/health', async () => ({ status: 'ok', contractVersion: '1.1.0', mockMode: process.env.MOCK_MODE === 'true', persistence: database ? 'postgres' : 'fixture' }));
app.post('/api/v1/webhooks/stripe', { config: { rawBody: true } }, async (request, reply) => {
  if (!database || !process.env.STRIPE_SECRET_KEY || !process.env.STRIPE_WEBHOOK_SECRET || process.env.STRIPE_WEBHOOK_SECRET.includes('<')) return fail(reply, 503, 'PAYMENTS_UNAVAILABLE', 'Stripe webhook verification is not configured.');
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
  let event: Stripe.Event;
  try { event = stripe.webhooks.constructEvent((request as FastifyRequest & { rawBody: string }).rawBody, request.headers['stripe-signature'] ?? '', process.env.STRIPE_WEBHOOK_SECRET); } catch { return fail(reply, 400, 'INVALID_WEBHOOK', 'Stripe webhook signature verification failed.'); }
  const inserted = await database.query<{ event_id: string }>('INSERT INTO payment_webhook_events (provider, event_id, payload) VALUES (\'stripe\',$1,$2) ON CONFLICT (provider,event_id) DO NOTHING RETURNING event_id', [event.id, JSON.stringify(event)]);
  if (!inserted.length) { const prior = await database.query<{ processed_at: string | null }>('SELECT processed_at FROM payment_webhook_events WHERE provider = \'stripe\' AND event_id = $1', [event.id]); if (prior[0]?.processed_at) return { received: true, duplicate: true }; }
  if (event.type === 'payment_intent.succeeded' || event.type === 'payment_intent.payment_failed') { const intent = event.data.object as Stripe.PaymentIntent; await database.query('UPDATE payment_attempts SET status = $1, provider_reference = $2 WHERE provider = \'stripe\' AND (provider_reference = $2 OR idempotency_key = $3)', [event.type.endsWith('succeeded') ? 'succeeded' : 'failed', intent.id, intent.metadata?.idempotencyKey ?? '']); }
  await database.query('UPDATE payment_webhook_events SET processed_at = now() WHERE provider = \'stripe\' AND event_id = $1', [event.id]);
  return { received: true };
});
app.get('/api/v1/session', async (request, reply) => { const a = auth(request, reply); if (!a) return; return { user: a, capabilities: a.role === 'admin' ? ['quotes:write', 'jobs:write', 'catalog:write'] : a.role === 'mechanic' ? ['jobs:read', 'jobs:write', 'messages:write'] : ['vehicles:read', 'requests:write', 'quotes:accept'] }; });
app.get('/api/v1/service-catalog', async () => ({ data: fixtureState.services, meta: { source: process.env.MOCK_MODE === 'true' ? 'fixture' : 'development-adapter' } }));
app.get('/api/v1/availability', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (!database) return { data: [], meta: { source: 'fixture' } }; const q = z.object({ mechanicId: z.string().uuid(), startsAt: z.string().datetime(), endsAt: z.string().datetime() }).safeParse(request.query); if (!q.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Availability query is invalid.', q.error.flatten().fieldErrors); const rows = await database.query('SELECT id, starts_at AS "startsAt", ends_at AS "endsAt", status FROM appointments WHERE mechanic_id = $1 AND status IN (\'held\',\'confirmed\',\'scheduled\') AND tstzrange(starts_at, ends_at, \'[)\') && tstzrange($2::timestamptz, $3::timestamptz, \'[)\')', [q.data.mechanicId, q.data.startsAt, q.data.endsAt]); return { data: rows, available: rows.length === 0 }; });
const holdSchema = z.object({ mechanicId: z.string().uuid(), startsAt: z.string().datetime(), endsAt: z.string().datetime(), expiresAt: z.string().datetime(), idempotencyKey: z.string().min(8) });
app.post('/api/v1/booking-holds', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer' || !bookingRepository) return fail(reply, 403, 'FORBIDDEN', 'Booking is unavailable for this actor or environment.'); const p = holdSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Booking hold is invalid.', p.error.flatten().fieldErrors); try { const hold = await bookingRepository.createHold({ customerId: a.id, mechanicId: p.data.mechanicId, startsAt: new Date(p.data.startsAt), endsAt: new Date(p.data.endsAt), expiresAt: new Date(p.data.expiresAt), idempotencyKey: p.data.idempotencyKey }); return reply.code(201).send({ data: hold }); } catch (error) { if ((error as { code?: string }).code === '23P01') return fail(reply, 409, 'BOOKING_CONFLICT', 'The selected mechanic slot is no longer available.'); throw error; } });
app.get('/api/v1/invoices', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer' || !invoiceRepository) return fail(reply, 403, 'FORBIDDEN', 'Invoice access is unavailable for this actor or environment.'); return { data: await invoiceRepository.listForCustomer(a.id) }; });
app.get('/api/v1/admin/jobs', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'admin' || !database) return fail(reply, 403, 'FORBIDDEN', 'Only admins may list operational jobs.'); return { data: await database.query('SELECT id, customer_id AS "customerId", mechanic_id AS "mechanicId", status, version, created_at AS "createdAt" FROM jobs ORDER BY created_at DESC') }; });
app.get('/api/v1/admin/service-requests', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'admin' || !serviceRequestRepository) return fail(reply, 403, 'FORBIDDEN', 'Only admins may list service requests.'); const query = z.object({ status: z.string().min(1).max(40).optional() }).safeParse(request.query); if (!query.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Service-request filters are invalid.', query.error.flatten().fieldErrors); return { data: await serviceRequestRepository.listForAdmin(query.data.status) }; });
app.post('/api/v1/admin/memberships', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'admin' || !database) return fail(reply, 403, 'FORBIDDEN', 'Only admins may provision memberships.'); const body = z.object({ email: z.string().email(), role: z.enum(['customer', 'mechanic', 'admin']) }).safeParse(request.body); if (!body.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Membership input is invalid.', body.error.flatten().fieldErrors); const business = await database.query<{ businessId: string }>('SELECT business_id AS "businessId" FROM memberships WHERE user_id = $1 AND role = \'admin\' LIMIT 1', [a.id]); if (!business[0]) return fail(reply, 403, 'FORBIDDEN', 'Admin business membership was not found.'); const user = await database.query<{ id: string; email: string }>('SELECT id, email FROM users WHERE lower(email) = lower($1)', [body.data.email]); if (!user[0]) return fail(reply, 404, 'NOT_FOUND', 'Create or invite this Supabase Auth user before provisioning membership.'); const membership = await database.query('INSERT INTO memberships (user_id, business_id, role) VALUES ($1,$2,$3) ON CONFLICT (user_id,business_id) DO UPDATE SET role = EXCLUDED.role RETURNING user_id AS "userId", business_id AS "businessId", role', [user[0].id, business[0].businessId, body.data.role]); return reply.code(201).send({ data: { ...membership[0], email: user[0].email } }); });
app.get('/api/v1/mechanic/jobs', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'mechanic' || !database) return fail(reply, 403, 'FORBIDDEN', 'Only mechanics may list assigned jobs.'); return { data: await database.query('SELECT id, customer_id AS "customerId", mechanic_id AS "mechanicId", status, version, created_at AS "createdAt" FROM jobs WHERE mechanic_id = $1 ORDER BY created_at DESC', [a.id]) }; });
app.post('/api/v1/payments', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer' || !database || !process.env.STRIPE_SECRET_KEY) return fail(reply, 503, 'PAYMENTS_UNAVAILABLE', 'Stripe payments are not configured.'); const p = z.object({ amountMinor: z.number().int().positive(), currency: z.string().length(3), idempotencyKey: z.string().min(8) }).safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Payment input is invalid.', p.error.flatten().fieldErrors); const stripe = new Stripe(process.env.STRIPE_SECRET_KEY); const intent = await stripe.paymentIntents.create({ amount: p.data.amountMinor, currency: p.data.currency.toLowerCase(), automatic_payment_methods: { enabled: true, allow_redirects: 'never' }, metadata: { customerId: a.id, idempotencyKey: p.data.idempotencyKey } }, { idempotencyKey: p.data.idempotencyKey }); await database.query('INSERT INTO payment_attempts (customer_id, provider, provider_reference, amount_minor, currency, status, idempotency_key) VALUES ($1,\'stripe\',$2,$3,$4,\'created\',$5) ON CONFLICT (customer_id,idempotency_key) DO NOTHING', [a.id, intent.id, p.data.amountMinor, p.data.currency.toUpperCase(), p.data.idempotencyKey]); return reply.code(201).send({ data: { id: intent.id, clientSecret: intent.client_secret, status: intent.status } }); });
app.post('/api/v1/payments/:id/refund', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'admin' || !database || !process.env.STRIPE_SECRET_KEY) return fail(reply, 503, 'PAYMENTS_UNAVAILABLE', 'Stripe refunds are not configured.'); const stripe = new Stripe(process.env.STRIPE_SECRET_KEY); const refund = await stripe.refunds.create({ payment_intent: (request.params as { id: string }).id }, { idempotencyKey: String(request.headers['idempotency-key'] ?? '') || undefined }); await database.query("UPDATE payment_attempts SET status = 'refunded' WHERE provider = 'stripe' AND provider_reference = $1", [(request.params as { id: string }).id]); return { data: { id: refund.id, status: refund.status } }; });
app.post('/api/v1/admin/service-requests/:id/quotes', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'admin' || !quoteJobRepository) return fail(reply, 403, 'FORBIDDEN', 'Only admins may issue quotes.'); const body = z.object({ customerId: z.string().uuid(), currency: z.string().length(3), lines: z.array(z.object({ description: z.string().min(1), amountMinor: z.number().int().nonnegative(), quantity: z.number().positive().optional() })).min(1) }).safeParse(request.body); if (!body.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Quote input is invalid.', body.error.flatten().fieldErrors); const quote = await quoteJobRepository.createQuote({ requestId: (request.params as { id: string }).id, ...body.data }); return reply.code(201).send({ data: quote }); });
app.get('/api/v1/vehicles', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can access household vehicles.'); if (vehicleRepository) return { data: await vehicleRepository.listForCustomer(a.id) }; return { data: fixtureState.vehicles.filter((v) => v.customerId === a.id) }; });
const vehicleSchema = z.object({ year: z.number().int().min(1886).max(2100), make: z.string().min(1).max(80), model: z.string().min(1).max(80), mileage: z.number().int().nonnegative().optional(), vin: z.string().length(17).optional() });
app.post('/api/v1/vehicles', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can create vehicles.'); const p = vehicleSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Vehicle input is invalid.', p.error.flatten().fieldErrors); if (vehicleRepository) { const v = await vehicleRepository.create(a.id, p.data); return reply.code(201).send({ data: v }); } const v = { id: `vehicle-${fixtureState.vehicles.length + 1}`, customerId: a.id, ...p.data }; fixtureState.vehicles.push(v); return reply.code(201).send({ data: v }); });
app.get('/api/v1/vehicles/:id/history', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can access vehicle history.'); const id = (request.params as { id: string }).id; if (vehicleRepository && z.string().uuid().safeParse(id).success) { const history = await vehicleRepository.historyForCustomer(id, a.id); if (!history) return fail(reply, 404, 'NOT_FOUND', 'Vehicle not found.'); return { data: history }; } const v = fixtureState.vehicles.find((x) => x.id === id && x.customerId === a.id); if (!v) return fail(reply, 404, 'NOT_FOUND', 'Vehicle not found.'); return { data: fixtureState.history.filter((h) => h.vehicleId === v.id) }; });
const requestSchema = z.object({ vehicleId: z.string(), category: z.string().min(1), symptoms: z.array(z.string()), notes: z.string().max(4000).optional(), attachmentIds: z.array(z.string()).optional() });
app.post('/api/v1/service-requests', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only customers can submit service requests.'); const p = requestSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Service request input is invalid.', p.error.flatten().fieldErrors); if (serviceRequestRepository) { const item = await serviceRequestRepository.create(a.id, p.data); if (!item) return fail(reply, 403, 'FORBIDDEN', 'Vehicle is not in your household.'); return reply.code(201).send({ data: item }); } if (!fixtureState.vehicles.some((v) => v.id === p.data.vehicleId && v.customerId === a.id)) return fail(reply, 403, 'FORBIDDEN', 'Vehicle is not in your household.'); const item = { id: `request-${fixtureState.requests.length + 1}`, customerId: a.id, status: 'submitted', ...p.data }; fixtureState.requests.push(item); return reply.code(201).send({ data: item }); });
const uploadSchema = z.object({ fileName: z.string().min(1).max(255), contentType: z.enum(['image/jpeg', 'image/png', 'image/webp', 'video/mp4']), sizeBytes: z.number().int().positive().max(25000000) });
app.post('/api/v1/uploads', async (request, reply) => { const a = auth(request, reply); if (!a) return; const p = uploadSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Upload metadata is invalid.', p.error.flatten().fieldErrors); const item = { id: `upload-${fixtureState.uploads.length + 1}`, ownerId: a.id, status: 'pending_local_adapter', ...p.data }; fixtureState.uploads.push(item); return reply.code(201).send({ data: item, meta: { provider: 'local-safe-adapter', uploadRequired: false } }); });
app.get('/api/v1/quotes/:id', async (request, reply) => { const a = auth(request, reply); if (!a) return; const id = (request.params as { id: string }).id; if (quoteJobRepository && z.string().uuid().safeParse(id).success && a.role === 'customer') { const q = await quoteJobRepository.getQuote(id, a.id); if (!q) return fail(reply, 404, 'NOT_FOUND', 'Quote not found.'); return { data: q }; } const q = fixtureState.quotes.find((x) => x.id === id); if (!q) return fail(reply, 404, 'NOT_FOUND', 'Quote not found.'); if (a.role === 'customer' && q.customerId !== a.id) return fail(reply, 403, 'FORBIDDEN', 'You are not allowed to access this quote.'); return { data: q }; });
app.get('/api/v1/jobs/:id', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = await jobFor(request, reply, a); if (!j) return; return { data: j }; });
const transitionSchema = z.object({ expectedVersion: z.number().int().positive(), status: z.enum(['scheduled','preparing','en_route','arrived','inspecting','awaiting_approval','repairing','completed','cancelled']) });
app.post('/api/v1/jobs/:id/transitions', async (request, reply) => { const a = auth(request, reply); if (!a) return; const id = (request.params as { id: string }).id; const p = transitionSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Transition input is invalid.', p.error.flatten().fieldErrors); if (!quoteJobRepository || !z.string().uuid().safeParse(id).success || !['mechanic','admin'].includes(a.role)) return fail(reply, 403, 'FORBIDDEN', 'Only assigned mechanics or admins may transition jobs.'); const job = await quoteJobRepository.transitionJob(id, a.id, a.role, p.data.expectedVersion, p.data.status); if (!job) return fail(reply, 409, 'STALE_VERSION', 'Job changed or is not assigned to this actor.'); return { data: job }; });
app.post('/api/v1/jobs/:id/completion-report', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'mechanic' || !quoteJobRepository) return fail(reply, 403, 'FORBIDDEN', 'Only the assigned mechanic may complete this job.'); const p = z.object({ summary: z.string().min(1).max(10000) }).safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Completion report is invalid.', p.error.flatten().fieldErrors); const result = await quoteJobRepository.completeJob((request.params as { id: string }).id, a.id, p.data.summary); if (!result) return fail(reply, 403, 'FORBIDDEN', 'Job is not assigned to this mechanic.'); return { data: result }; });
app.get('/api/v1/jobs/:id/findings', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = await jobFor(request, reply, a); if (!j) return; const id = (request.params as { id: string }).id; if (repairRoomRepository && z.string().uuid().safeParse(id).success) return { data: await repairRoomRepository.listFindings(id) }; return { data: fixtureState.findings.filter((x) => x.jobId === j.id) }; });
app.post('/api/v1/jobs/:id/findings', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = await jobFor(request, reply, a); if (!j) return; const id = (request.params as { id: string }).id; if (a.role !== 'mechanic' || !repairRoomRepository || !z.string().uuid().safeParse(id).success) return fail(reply, 403, 'FORBIDDEN', 'Only the assigned mechanic may add findings.'); const p = z.object({ category: z.enum(['recommended_now','plan_for_later','monitor']), note: z.string().min(1).max(10000), attachmentId: z.string().uuid().optional() }).safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Finding is invalid.', p.error.flatten().fieldErrors); return reply.code(201).send({ data: await repairRoomRepository.addFinding(id, a.id, p.data) }); });
app.get('/api/v1/jobs/:id/messages', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = await jobFor(request, reply, a); if (!j) return; const id = (request.params as { id: string }).id; if (repairRoomRepository && z.string().uuid().safeParse(id).success) return { data: await repairRoomRepository.listMessages(id) }; return { data: fixtureState.messages.filter((x) => x.jobId === j.id) }; });
const messageSchema = z.object({ body: z.string().min(1).max(4000) });
app.post('/api/v1/jobs/:id/messages', async (request, reply) => { const a = auth(request, reply); if (!a) return; const j = await jobFor(request, reply, a); if (!j) return; const key = request.headers['idempotency-key']; if (typeof key !== 'string' || key.length < 8) return fail(reply, 422, 'VALIDATION_ERROR', 'Idempotency-Key header is required.'); const p = messageSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Message is invalid.', p.error.flatten().fieldErrors); const id = (request.params as { id: string }).id; if (repairRoomRepository && z.string().uuid().safeParse(id).success) return reply.code(201).send({ data: await repairRoomRepository.addMessage(id, a.id, p.data.body) }); const item = { id: `message-${fixtureState.messages.length + 1}`, jobId: j.id, senderId: a.id, createdAt: new Date().toISOString(), ...p.data }; fixtureState.messages.push(item); return reply.code(201).send({ data: item }); });
const acceptSchema = z.object({ expectedVersion: z.number().int().positive(), idempotencyKey: z.string().min(8) });
app.post('/api/v1/quotes/:id/accept', async (request, reply) => { const a = auth(request, reply); if (!a) return; if (a.role !== 'customer') return fail(reply, 403, 'FORBIDDEN', 'Only the customer may accept a quote.'); const id = (request.params as { id: string }).id; const p = acceptSchema.safeParse(request.body); if (!p.success) return fail(reply, 422, 'VALIDATION_ERROR', 'Acceptance input is invalid.'); if (quoteJobRepository && z.string().uuid().safeParse(id).success) { const result = await quoteJobRepository.acceptQuote(id, a.id, p.data.expectedVersion); if (result.kind === 'not_found') return fail(reply, 404, 'NOT_FOUND', 'Quote not found.'); if (result.kind === 'stale') return fail(reply, 409, 'STALE_VERSION', 'Quote changed; retrieve the latest version before accepting.'); if (result.kind === 'not_acceptable') return fail(reply, 409, 'QUOTE_NOT_ACCEPTABLE', 'Only issued quotes can be accepted.'); return { data: result.quote }; } const q = fixtureState.quotes.find((x) => x.id === id); if (!q || q.customerId !== a.id) return fail(reply, 404, 'NOT_FOUND', 'Quote not found.'); if (p.data.expectedVersion !== q.version) return fail(reply, 409, 'STALE_VERSION', 'Quote changed; retrieve the latest version before accepting.'); if (q.status !== 'issued') return fail(reply, 409, 'QUOTE_NOT_ACCEPTABLE', 'Only issued quotes can be accepted.'); q.status = 'accepted'; q.version += 1; return { data: q }; });
app.setErrorHandler((err, request, reply) => { request.log.error(err); return fail(reply, 500, 'INTERNAL_ERROR', 'The server could not complete the request.'); });
await app.listen({ port: Number(process.env.PORT ?? 3000), host: process.env.HOST ?? '127.0.0.1' });
