import type { Database } from './client.js';

export function createVehicleRepository(db: Database) {
  return {
    async listForCustomer(customerId: string) { return db.query('SELECT id, customer_id AS "customerId", year, make, model, mileage, vin FROM vehicles WHERE customer_id = $1 ORDER BY created_at DESC', [customerId]); },
    async create(customerId: string, input: { year: number; make: string; model: string; mileage?: number; vin?: string }) { const rows = await db.query('INSERT INTO vehicles (customer_id, year, make, model, mileage, mileage_recorded_at, vin) VALUES ($1,$2,$3,$4,$5::integer,CASE WHEN $5::integer IS NULL THEN NULL ELSE now() END,$6) RETURNING id, customer_id AS "customerId", year, make, model, mileage, vin', [customerId, input.year, input.make, input.model, input.mileage ?? null, input.vin ?? null]); return rows[0]; },
    async historyForCustomer(vehicleId: string, customerId: string) { const vehicle = await db.query('SELECT id FROM vehicles WHERE id = $1 AND customer_id = $2', [vehicleId, customerId]); if (!vehicle[0]) return null; return db.query('SELECT id, category, status, created_at AS "createdAt" FROM service_requests WHERE vehicle_id = $1 AND customer_id = $2 ORDER BY created_at DESC', [vehicleId, customerId]); }
  };
}

export function createServiceRequestRepository(db: Database) {
  return { async create(customerId: string, input: { vehicleId: string; category: string; symptoms: string[]; notes?: string }) { const rows = await db.query('INSERT INTO service_requests (customer_id, vehicle_id, category, symptoms, delivery_mode) SELECT $1, v.id, $2, $3, CASE WHEN $2 = \'bodywork\' THEN \'shop\' ELSE \'mobile\' END FROM vehicles v WHERE v.id = $4 AND v.customer_id = $1 RETURNING id, customer_id AS "customerId", vehicle_id AS "vehicleId", category, symptoms, status, created_at', [customerId, input.category, JSON.stringify({ selected: input.symptoms, notes: input.notes ?? null }), input.vehicleId]); return rows[0] ?? null; }, async listForAdmin(status?: string) { const rows = await db.query<{ id: string; customerId: string; vehicleId: string; category: string; symptoms: string | Record<string, unknown>; status: string; createdAt: string; deliveryMode: string; customerEmail: string; year: number; make: string; model: string }>('SELECT sr.id, sr.customer_id AS "customerId", sr.vehicle_id AS "vehicleId", sr.category, sr.symptoms, sr.delivery_mode AS "deliveryMode", sr.status, sr.created_at AS "createdAt", u.email AS "customerEmail", v.year, v.make, v.model FROM service_requests sr JOIN users u ON u.id = sr.customer_id JOIN vehicles v ON v.id = sr.vehicle_id WHERE ($1::text IS NULL OR sr.status = $1) ORDER BY sr.created_at DESC', [status ?? null]); return rows.map(row => { const parsed = typeof row.symptoms === 'string' ? JSON.parse(row.symptoms) as { selected?: string[]; notes?: string } : row.symptoms as { selected?: string[]; notes?: string }; return { ...row, symptoms: parsed.selected ?? [], notes: parsed.notes ?? null }; }); } };
}

export function createBookingRepository(db: Database) {
  return {
    async createHold(input: { customerId: string; mechanicId: string; startsAt: Date; endsAt: Date; expiresAt: Date; idempotencyKey: string }) {
      return db.withTransaction(async (client) => {
        const existing = await client.query('SELECT id, status, expires_at AS "expiresAt" FROM booking_holds WHERE customer_id = $1 AND idempotency_key = $2', [input.customerId, input.idempotencyKey]);
        if (existing.rows[0]) return existing.rows[0];
        await client.query("UPDATE booking_holds SET status = 'expired' WHERE status = 'active' AND expires_at <= now()");
        const rows = await client.query('INSERT INTO booking_holds (customer_id, mechanic_id, starts_at, ends_at, expires_at, status, idempotency_key) VALUES ($1,$2,$3,$4,$5,\'active\',$6) RETURNING id, customer_id AS "customerId", mechanic_id AS "mechanicId", starts_at AS "startsAt", ends_at AS "endsAt", expires_at AS "expiresAt", status', [input.customerId, input.mechanicId, input.startsAt, input.endsAt, input.expiresAt, input.idempotencyKey]);
        return rows.rows[0];
      });
    },
    async confirmHold(holdId: string, customerId: string) { return db.withTransaction(async (client) => { const hold = await client.query('SELECT * FROM booking_holds WHERE id = $1 AND customer_id = $2 FOR UPDATE', [holdId, customerId]); if (!hold.rows[0] || hold.rows[0].status !== 'active' || new Date(hold.rows[0].expires_at) <= new Date()) return null; const appointment = await client.query('INSERT INTO appointments (customer_id, mechanic_id, starts_at, ends_at, timezone, status, version, hold_id, idempotency_key) VALUES ($1,$2,$3,$4,\'America/New_York\',\'confirmed\',1,$5,$6) RETURNING id, customer_id AS "customerId", mechanic_id AS "mechanicId", starts_at AS "startsAt", ends_at AS "endsAt", status, hold_id AS "holdId"', [customerId, hold.rows[0].mechanic_id, hold.rows[0].starts_at, hold.rows[0].ends_at, holdId, `confirm-${holdId}`]); const job = await client.query('INSERT INTO jobs (appointment_id, customer_id, mechanic_id, status, version) VALUES ($1,$2,$3,\'scheduled\',1) RETURNING id, appointment_id AS "appointmentId", customer_id AS "customerId", mechanic_id AS "mechanicId", status, version', [appointment.rows[0].id, customerId, hold.rows[0].mechanic_id]); await client.query("UPDATE booking_holds SET status = 'converted' WHERE id = $1", [holdId]); return { appointment: appointment.rows[0], job: job.rows[0] }; }); },
    async listMechanics(customerId: string) { return db.query('SELECT DISTINCT u.id, u.email AS "displayName" FROM users u JOIN memberships mechanic_membership ON mechanic_membership.user_id = u.id WHERE mechanic_membership.role = \'mechanic\' AND EXISTS (SELECT 1 FROM memberships customer_membership WHERE customer_membership.user_id = $1 AND customer_membership.business_id = mechanic_membership.business_id) ORDER BY u.email', [customerId]); },
    async cancelAppointment(input: { appointmentId: string; actorId: string; role: string; reason?: string }) {
      return db.withTransaction(async (client) => {
        const current = await client.query('SELECT id, customer_id AS "customerId", mechanic_id AS "mechanicId", starts_at AS "startsAt", status, version FROM appointments WHERE id = $1 FOR UPDATE', [input.appointmentId]);
        const appointment = current.rows[0];
        if (!appointment || !['confirmed', 'scheduled'].includes(appointment.status)) return { kind: 'not_found' as const };
        const participant = input.role === 'admin' || (input.role === 'customer' && appointment.customerId === input.actorId) || (input.role === 'mechanic' && appointment.mechanicId === input.actorId);
        if (!participant) return { kind: 'forbidden' as const };
        const cutoff = new Date(Date.now() + 2 * 60 * 60 * 1000);
        if (input.role !== 'admin' && new Date(appointment.startsAt) < cutoff) return { kind: 'cutoff' as const };
        const updated = await client.query("UPDATE appointments SET status = 'cancelled', version = version + 1, cancelled_at = now(), cancelled_by = $2, cancellation_reason = $3 WHERE id = $1 RETURNING id, customer_id AS \"customerId\", mechanic_id AS \"mechanicId\", starts_at AS \"startsAt\", status, version, cancelled_at AS \"cancelledAt\", cancellation_reason AS \"cancellationReason\"", [input.appointmentId, input.actorId, input.reason ?? null]);
        await client.query('INSERT INTO audit_events (actor_id, action, resource_type, resource_id, payload) VALUES ($1, $2, $3, $4, $5)', [input.actorId, 'appointment.cancelled', 'appointment', input.appointmentId, JSON.stringify({ reason: input.reason ?? null })]);
        return { kind: 'cancelled' as const, appointment: updated.rows[0] };
      });
    },
    async rescheduleAppointment(input: { appointmentId: string; holdId: string; actorId: string; role: string; expectedVersion: number; reason?: string }) {
      return db.withTransaction(async (client) => {
        const current = await client.query('SELECT id, customer_id AS "customerId", mechanic_id AS "mechanicId", starts_at AS "startsAt", status, version FROM appointments WHERE id = $1 FOR UPDATE', [input.appointmentId]);
        const appointment = current.rows[0];
        if (!appointment || !['confirmed', 'scheduled'].includes(appointment.status)) return { kind: 'not_found' as const };
        if (appointment.version !== input.expectedVersion) return { kind: 'stale' as const };
        const participant = input.role === 'admin' || (input.role === 'customer' && appointment.customerId === input.actorId) || (input.role === 'mechanic' && appointment.mechanicId === input.actorId);
        if (!participant) return { kind: 'forbidden' as const };
        if (input.role !== 'admin' && new Date(appointment.startsAt) < new Date(Date.now() + 2 * 60 * 60 * 1000)) return { kind: 'cutoff' as const };
        const hold = await client.query('SELECT * FROM booking_holds WHERE id = $1 AND customer_id = $2 FOR UPDATE', [input.holdId, appointment.customerId]);
        if (!hold.rows[0] || hold.rows[0].status !== 'active' || new Date(hold.rows[0].expires_at) <= new Date() || hold.rows[0].mechanic_id !== appointment.mechanicId) return { kind: 'hold_invalid' as const };
        const next = await client.query('INSERT INTO appointments (quote_id, customer_id, mechanic_id, starts_at, ends_at, timezone, status, version, hold_id, idempotency_key, rescheduled_from_id) SELECT appointment.quote_id, appointment.customer_id, appointment.mechanic_id, hold.starts_at, hold.ends_at, appointment.timezone, \'confirmed\', 1, hold.id, $2, $3 FROM appointments appointment JOIN booking_holds hold ON hold.id = $1 WHERE appointment.id = $4 RETURNING id, customer_id AS "customerId", mechanic_id AS "mechanicId", starts_at AS "startsAt", ends_at AS "endsAt", status, version, hold_id AS "holdId", rescheduled_from_id AS "rescheduledFromId"', [input.holdId, `reschedule-${input.appointmentId}-${input.holdId}`, input.appointmentId, input.appointmentId]);
        await client.query("UPDATE appointments SET status = 'rescheduled', version = version + 1, rescheduled_to_id = $2, rescheduled_at = now(), rescheduled_by = $3, rescheduling_reason = $4 WHERE id = $1", [input.appointmentId, next.rows[0].id, input.actorId, input.reason ?? null]);
        await client.query('UPDATE jobs SET appointment_id = $2, version = version + 1 WHERE appointment_id = $1', [input.appointmentId, next.rows[0].id]);
        await client.query("UPDATE booking_holds SET status = 'converted' WHERE id = $1", [input.holdId]);
        await client.query('INSERT INTO audit_events (actor_id, action, resource_type, resource_id, payload) VALUES ($1, $2, $3, $4, $5)', [input.actorId, 'appointment.rescheduled', 'appointment', input.appointmentId, JSON.stringify({ newAppointmentId: next.rows[0].id, reason: input.reason ?? null })]);
        return { kind: 'rescheduled' as const, appointment: next.rows[0] };
      });
    }
  };
}

export function createPaymentRepository(db: Database) {
  return { async createAttempt(input: { customerId: string; invoiceId?: string; amountMinor: number; currency: string; idempotencyKey: string }) { const rows = await db.query('INSERT INTO payment_attempts (customer_id, invoice_id, provider, amount_minor, currency, status, idempotency_key) VALUES ($1,$2,\'stripe\',$3,$4,\'created\',$5) ON CONFLICT DO NOTHING RETURNING id, status, invoice_id AS "invoiceId", amount_minor AS "amountMinor", currency, idempotency_key AS "idempotencyKey"', [input.customerId, input.invoiceId ?? null, input.amountMinor, input.currency, input.idempotencyKey]); return rows[0]; } };
}

export function createRepairRoomRepository(db: Database) {
  return {
    async listMessages(jobId: string) { return db.query('SELECT id, job_id AS "jobId", sender_id AS "senderId", body, created_at AS "createdAt" FROM job_messages WHERE job_id = $1 ORDER BY created_at', [jobId]); },
    async addMessage(jobId: string, senderId: string, body: string) { const rows = await db.query('INSERT INTO job_messages (job_id, sender_id, body) VALUES ($1,$2,$3) RETURNING id, job_id AS "jobId", sender_id AS "senderId", body, created_at AS "createdAt"', [jobId, senderId, body]); return rows[0]; },
    async listFindings(jobId: string) { return db.query('SELECT id, job_id AS "jobId", mechanic_id AS "mechanicId", category, note, attachment_id AS "attachmentId", created_at AS "createdAt" FROM inspection_findings WHERE job_id = $1 ORDER BY created_at', [jobId]); },
    async addFinding(jobId: string, mechanicId: string, input: { category: string; note: string; attachmentId?: string }) { const rows = await db.query('INSERT INTO inspection_findings (job_id, mechanic_id, category, note, attachment_id) VALUES ($1,$2,$3,$4,$5) RETURNING id, job_id AS "jobId", mechanic_id AS "mechanicId", category, note, attachment_id AS "attachmentId", created_at AS "createdAt"', [jobId, mechanicId, input.category, input.note, input.attachmentId ?? null]); return rows[0]; }
  };
}

export function createInvoiceRepository(db: Database) {
  return { async listForCustomer(customerId: string) { return db.query('SELECT id, job_id AS "jobId", customer_id AS "customerId", currency, total_minor AS "totalMinor", status, due_at AS "dueAt", created_at AS "createdAt" FROM invoices WHERE customer_id = $1 ORDER BY created_at DESC', [customerId]); }, async getForCustomer(id: string, customerId: string) { const rows = await db.query('SELECT id, job_id AS "jobId", customer_id AS "customerId", currency, total_minor AS "totalMinor", status, due_at AS "dueAt", created_at AS "createdAt" FROM invoices WHERE id = $1 AND customer_id = $2', [id, customerId]); return rows[0]; }, async createForJob(jobId: string, currency: string, totalMinor: number) { const rows = await db.query('INSERT INTO invoices (job_id, customer_id, currency, total_minor, status) SELECT j.id, j.customer_id, $2, $3, \'open\' FROM jobs j WHERE j.id = $1 RETURNING id, job_id AS "jobId", customer_id AS "customerId", currency, total_minor AS "totalMinor", status, due_at AS "dueAt", created_at AS "createdAt"', [jobId, currency, totalMinor]); return rows[0]; } };
}

export function createQuoteJobRepository(db: Database) {
  return {
    async createQuote(input: { requestId: string; customerId: string; currency: string; lines: Array<{ description: string; amountMinor: number; quantity?: number }> }) { return db.withTransaction(async (client) => { const total = input.lines.reduce((sum, line) => sum + line.amountMinor * (line.quantity ?? 1), 0); const quote = await client.query('INSERT INTO quotes (request_id, customer_id, version, status, currency, total_minor) VALUES ($1,$2,1,\'issued\',$3,$4) RETURNING id, request_id AS "requestId", customer_id AS "customerId", version, status, currency, total_minor AS "totalMinor"', [input.requestId, input.customerId, input.currency, total]); for (const line of input.lines) await client.query('INSERT INTO quote_lines (quote_id, description, amount_minor, quantity) VALUES ($1,$2,$3,$4)', [quote.rows[0].id, line.description, line.amountMinor, line.quantity ?? 1]); await client.query("UPDATE service_requests SET status = 'quoted' WHERE id = $1 AND customer_id = $2", [input.requestId, input.customerId]); return quote.rows[0]; }); },
    async getQuote(id: string, customerId: string) { const rows = await db.query('SELECT q.id, q.request_id AS "requestId", q.customer_id AS "customerId", q.version, q.status, q.currency, q.total_minor AS "totalMinor", COALESCE(json_agg(json_build_object(\'description\',l.description,\'amountMinor\',l.amount_minor,\'quantity\',l.quantity)) FILTER (WHERE l.id IS NOT NULL), \'[]\') AS lines FROM quotes q LEFT JOIN quote_lines l ON l.quote_id = q.id WHERE q.id = $1 AND q.customer_id = $2 GROUP BY q.id', [id, customerId]); return rows[0]; },
    async acceptQuote(id: string, customerId: string, expectedVersion: number) { return db.withTransaction(async (client) => { const current = await client.query('SELECT * FROM quotes WHERE id = $1 AND customer_id = $2 FOR UPDATE', [id, customerId]); if (!current.rows[0]) return { kind: 'not_found' as const }; if (current.rows[0].version !== expectedVersion) return { kind: 'stale' as const, quote: current.rows[0] }; if (current.rows[0].status !== 'issued') return { kind: 'not_acceptable' as const }; const accepted = await client.query('UPDATE quotes SET status = \'accepted\', version = version + 1 WHERE id = $1 RETURNING id, customer_id AS "customerId", version, status, currency, total_minor AS "totalMinor"', [id]); await client.query('INSERT INTO approvals (quote_id, quote_version, actor_id, decision, accepted_total_minor) VALUES ($1,$2,$3,\'accepted\',$4)', [id, expectedVersion, customerId, current.rows[0].total_minor]); return { kind: 'accepted' as const, quote: accepted.rows[0] }; }); },
    async transitionJob(id: string, actorId: string, role: string, expectedVersion: number, status: string) { const rows = await db.query('UPDATE jobs SET status = $1, version = version + 1 WHERE id = $2 AND version = $3 AND (($4 = \'mechanic\' AND mechanic_id = $5) OR $4 = \'admin\') RETURNING id, customer_id AS "customerId", mechanic_id AS "mechanicId", status, version', [status, id, expectedVersion, role, actorId]); return rows[0]; },
    async completeJob(id: string, mechanicId: string, summary: string) { return db.withTransaction(async (client) => { const job = await client.query('UPDATE jobs SET status = \'completed\', version = version + 1 WHERE id = $1 AND mechanic_id = $2 RETURNING id, customer_id AS "customerId", mechanic_id AS "mechanicId", status, version', [id, mechanicId]); if (!job.rows[0]) return null; const report = await client.query('INSERT INTO completion_reports (job_id, mechanic_id, summary) VALUES ($1,$2,$3) ON CONFLICT (job_id) DO UPDATE SET summary = EXCLUDED.summary, completed_at = now() RETURNING id, job_id AS "jobId", summary, completed_at AS "completedAt"', [id, mechanicId, summary]); return { job: job.rows[0], report: report.rows[0] }; }); }
  };
}
